// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentSession() {
  return window['go']['gui']['App']['CurrentSession']();
}

export function GetDailyTotals(arg1) {
  return window['go']['gui']['App']['GetDailyTotals'](arg1);
}

export function GetStats(arg1) {
  return window['go']['gui']['App']['GetStats'](arg1);
}

export function GetTagBreakdown(arg1) {
  return window['go']['gui']['App']['GetTagBreakdown'](arg1);
}

export function PauseSession() {
  return window['go']['gui']['App']['PauseSession']();
}

export function ResumeSession() {
  return window['go']['gui']['App']['ResumeSession']();
}

export function StartSession(arg1, arg2, arg3) {
  return window['go']['gui']['App']['StartSession'](arg1, arg2, arg3);
}

export function StopSession() {
  return window['go']['gui']['App']['StopSession']();
}
