// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function CurrentSession():Promise<gui.SessionDTO>;

export function PauseSession():Promise<gui.SessionDTO>;

export function ResumeSession():Promise<gui.SessionDTO>;

export function StartSession(arg1:string,arg2:string,arg3:string):Promise<gui.SessionDTO>;

export function StopSession():Promise<gui.SessionDTO>;
